-- =============================================================================
-- Recall Alert — Full Database Schema
-- Run this on a fresh PostgreSQL database (RDS or local).
--
-- Fixes vs. original create_tables.py:
--   1. users:   added password_hash column (required for auth)
--   2. recalls: added firm_name, distribution_pattern (required by recall_update.py)
--              upc raised to VARCHAR(50) to handle FDA synthetic keys (e.g. "FDA-R-001-2024")
--              product_name raised to VARCHAR(500), reason/severity widened
--   3. alerts:  renamed sent_at → created_at (matches recall_update.py INSERT)
--   4. Added UNIQUE constraint on recalls(upc, recall_date) for ON CONFLICT upsert
-- =============================================================================

-- Users
CREATE TABLE IF NOT EXISTS users (
    id            SERIAL PRIMARY KEY,
    email         VARCHAR(255) UNIQUE NOT NULL,
    name          VARCHAR(255),
    password_hash VARCHAR(255),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Products (scanned items, Open Food Facts cache)
CREATE TABLE IF NOT EXISTS products (
    id           SERIAL PRIMARY KEY,
    upc          VARCHAR(13) UNIQUE NOT NULL,
    product_name VARCHAR(255),
    brand_name   VARCHAR(255),
    category     VARCHAR(100),
    ingredients  TEXT,
    image_url    VARCHAR(500),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Recalls (FDA + USDA, refreshed every 6 hours by recall_update.py)
CREATE TABLE IF NOT EXISTS recalls (
    id                   SERIAL PRIMARY KEY,
    upc                  VARCHAR(50)  NOT NULL,   -- may be "FDA-<recall_number>" if no UPC
    product_name         VARCHAR(500) NOT NULL,
    brand_name           VARCHAR(200),
    recall_date          DATE         NOT NULL,
    reason               TEXT         NOT NULL,
    severity             VARCHAR(50),              -- "Class I / II / III"
    firm_name            VARCHAR(200),
    distribution_pattern VARCHAR(500),
    source               VARCHAR(50),              -- "FDA" | "USDA"
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT recalls_upc_date_unique UNIQUE (upc, recall_date)
);

-- User grocery lists
CREATE TABLE IF NOT EXISTS user_carts (
    id           SERIAL PRIMARY KEY,
    user_id      INTEGER REFERENCES users(id) ON DELETE CASCADE,
    product_upc  VARCHAR(13) NOT NULL,
    product_name VARCHAR(255),
    brand_name   VARCHAR(255),
    added_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, product_upc)
);

-- Recall alerts (generated by recall_update.py when a cart item is recalled)
CREATE TABLE IF NOT EXISTS alerts (
    id          SERIAL PRIMARY KEY,
    user_id     INTEGER REFERENCES users(id)   ON DELETE CASCADE,
    recall_id   INTEGER REFERENCES recalls(id) ON DELETE CASCADE,
    product_upc VARCHAR(50)  NOT NULL,
    product_name VARCHAR(255),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    viewed      BOOLEAN DEFAULT FALSE,
    email_sent  BOOLEAN DEFAULT FALSE
);
