-- =============================================================================
-- Recall Alert — Seed Data (exported from original RDS 2026-02-26)
-- Run AFTER create_tables.sql
-- =============================================================================

-- PRODUCTS (201 rows)
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41190468935','Organic Almond Butter','Nature''s Path',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70038640196','Peanut Butter Cups','Reese''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11110787835','Broccoli Florets Frozen','Green Giant',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41303054109','Plain Greek Yogurt','Chobani',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('52100032283','Frozen Spinach','Green Giant',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('688267008757','Organic Baby Food Carrots','Plum Organics',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('12000161551','Corn Flakes Cereal','Kellogg''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41755001054','Vanilla Ice Cream','Ben & Jerry''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('78742361383','Frozen Pizza Pepperoni','DiGiorno',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('37600437301','Chicken Broth','Swanson',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11110861122','Sweet Peas Frozen','Birds Eye',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41497434954','Orange Juice Pulp Free','Tropicana',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('25000042126','Macaroni & Cheese','Kraft',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41130581298','Granola Bars Chocolate','Nature Valley',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41220067183','Tomato Sauce','Prego',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11150541947','Canned Corn','Del Monte',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('688267141218','Fruit Pouches Mixed Berry','Plum Organics',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70330632776','Grape Jelly','Welch''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('21000016631','BBQ Sauce Original','Sweet Baby Ray''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41303091234','Greek Yogurt Vanilla','Chobani',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('52100081234','Oreo Cookies','Nabisco',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70177031312','Salsa Medium','Tostitos',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41190001234','Maple Syrup','Nature''s Path',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('12000101234','Frosted Flakes','Kellogg''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41755021234','Chunky Monkey Ice Cream','Ben & Jerry''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('78742051234','Frozen Pizza Supreme','DiGiorno',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('37600111234','Vegetable Broth','Swanson',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11110981234','Green Beans Frozen','Birds Eye',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41497091234','Apple Juice','Tropicana',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('25000051234','Velveeta Shells & Cheese','Kraft',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41130061234','Protein Bars Peanut Butter','Nature Valley',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41220081234','Alfredo Sauce','Prego',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11150081234','Canned Green Beans','Del Monte',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('688267121234','Organic Applesauce','Plum Organics',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70330081234','Strawberry Preserves','Welch''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('21000081234','Honey BBQ Sauce','Sweet Baby Ray''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41303111234','Greek Yogurt Blueberry','Chobani',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('52100121234','Wheat Thins Crackers','Nabisco',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70177081234','Queso Dip','Tostitos',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41190121234','Peanut Butter Crunchy','Nature''s Path',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('12000201234','Rice Krispies','Kellogg''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41755101234','Half Baked Ice Cream','Ben & Jerry''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('78742101234','Frozen Pizza Four Cheese','DiGiorno',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('37600201234','Beef Broth','Swanson',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11111001234','Peas & Carrots Frozen','Birds Eye',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41497201234','Grapefruit Juice','Tropicana',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('25000101234','Easy Mac Microwave','Kraft',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41130101234','Chewy Granola Bars','Nature Valley',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41220101234','Marinara Sauce','Prego',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11150101234','Canned Peas','Del Monte',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41190468831','Organic Granola Original','Nature''s Path',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70038349228','Peanut Butter','Reese''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41303011727','Non-Fat Greek Yogurt','Chobani',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('52100120175','Triscuit Crackers','Nabisco',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41190400089','Flax Plus Cereal','Nature''s Path',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('12000161605','Raisin Bran Cereal','Kellogg''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41755069498','Phish Food Ice Cream','Ben & Jerry''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('78742145938','Thin Crust Pizza Margherita','DiGiorno',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('37600105743','Low Sodium Chicken Broth','Swanson',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11110840325','Steamfresh Carrots','Birds Eye',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41497605132','Lemonade','Tropicana',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('25000087424','Three Cheese Shells','Kraft',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41130589201','Crunchy Granola Bars Oats','Nature Valley',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41220632787','Roasted Garlic Sauce','Prego',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11150540803','Fruit Cocktail','Del Monte',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('688267039256','Mango Baby Food','Plum Organics',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70330606746','Strawberry Spread','Welch''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('21000658251','Hickory Brown Sugar BBQ','Sweet Baby Ray''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41303051085','Low-Fat Greek Yogurt Peach','Chobani',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('52100043658','Premium Saltines','Nabisco',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70177453893','Scoops Tortilla Chips','Tostitos',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41190017812','EnviroKidz Cereal','Nature''s Path',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('12000508707','Frosted Mini-Wheats','Kellogg''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41755090461','Chocolate Fudge Brownie','Ben & Jerry''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('78742041063','Stuffed Crust Pizza Pepperoni','DiGiorno',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('37600430715','Organic Chicken Broth','Swanson',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11110854063','Italian Green Beans','Birds Eye',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41497434817','Cranberry Juice Cocktail','Tropicana',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('25000031328','Deluxe Four Cheese','Kraft',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41130581304','Protein Peanut Butter Bars','Nature Valley',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41220632800','Chunky Garden Sauce','Prego',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11150183058','Mandarin Oranges','Del Monte',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('688267141157','Pear Baby Food','Plum Organics',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70330726048','Grape Jam','Welch''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('21000658220','Original BBQ Sauce','Sweet Baby Ray''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41303052075','Flip Greek Yogurt Almond','Chobani',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('52100096340','Chips Ahoy Chewy','Nabisco',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70177031299','Original Restaurant Style','Tostitos',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41190002290','Pumpkin Flax Granola','Nature''s Path',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('12000429972','Corn Pops Cereal','Kellogg''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41755069504','The Tonight Dough','Ben & Jerry''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('78742145815','Hand Tossed Pizza Three Meat','DiGiorno',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('37600107389','Flavor Boost Chicken','Swanson',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11110860750','Chopped Spinach Frozen','Birds Eye',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41497434510','Fruit Punch','Tropicana',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('25000155727','White Cheddar Shells','Kraft',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41130589188','Sweet & Salty Granola Bars','Nature Valley',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41220632817','Heart Healthy Sauce','Prego',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11150540827','Pineapple Chunks','Del Monte',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('688267141140','Blueberry Baby Food','Plum Organics',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70330606708','Mixed Fruit Spread','Welch''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('21000658275','Garlic & Brown Sugar BBQ','Sweet Baby Ray''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41303054024','Greek Yogurt Key Lime','Chobani',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('52100096357','Chips Ahoy Original','Nabisco',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70177484077','Bite Size Rounds','Tostitos',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41190410514','Qi''a Superfood Cereal','Nature''s Path',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('12000161643','All-Bran Cereal','Kellogg''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41755069467','Milk & Cookies Ice Cream','Ben & Jerry''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('78742361406','Croissant Crust Pizza','DiGiorno',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('37600226455','Crafted Bone Broth Chicken','Swanson',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11110840318','Steamfresh Broccoli Cuts','Birds Eye',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41497605125','Pink Lemonade','Tropicana',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('25000027994','Velveeta Original','Kraft',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41130581281','Crunchy Granola Bars Peanut','Nature Valley',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41220067176','Meat Sauce','Prego',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11150540834','Sliced Pears','Del Monte',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('688267141133','Strawberry Banana Baby Food','Plum Organics',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70330606722','Apple Jelly','Welch''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('21000658237','Honey BBQ Sauce','Sweet Baby Ray''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41303054000','Vanilla Greek Yogurt','Chobani',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('52100120168','Wheat Thins Original','Nabisco',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70177031336','Multigrain Scoops','Tostitos',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41190410491','Love Crunch Granola','Nature''s Path',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('12000161629','Crispix Cereal','Kellogg''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41755090478','Americone Dream Ice Cream','Ben & Jerry''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('78742145822','Croissant Crust Spinach','DiGiorno',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('37600106238','Organic Vegetable Broth','Swanson',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11110874047','Protein Blend Vegetables','Birds Eye',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41497434503','Grape Juice','Tropicana',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('25000090455','Thick N Creamy Mac','Kraft',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41130581311','Protein Oats Honey Bars','Nature Valley',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41220067152','Fresh Mushroom Sauce','Prego',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11150183041','Diced Peaches','Del Monte',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('688267039232','Butternut Squash Baby Food','Plum Organics',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70330606685','Blackberry Spread','Welch''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('21000658244','Teriyaki BBQ Sauce','Sweet Baby Ray''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41303054093','Coffee Greek Yogurt','Chobani',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('52100043641','Honey Maid Grahams','Nabisco',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70177484084','Crispy Rounds','Tostitos',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41190017805','Gorilla Munch Cereal','Nature''s Path',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('12000429989','Apple Jacks Cereal','Kellogg''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41755090485','Peanut Butter Cup Ice Cream','Ben & Jerry''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('78742041087','Personal Size Pizza Pepperoni','DiGiorno',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('37600432269','Sipping Bone Broth Ginger','Swanson',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11110781543','Riced Cauliflower','Birds Eye',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41497605118','Apple Juice','Tropicana',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('25000031311','Sharp Cheddar Mac','Kraft',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41220632824','Farmers Market Sauce','Prego',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11150540810','Mixed Fruit','Del Monte',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('688267039249','Green Bean Baby Food','Plum Organics',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70330726055','Raspberry Preserves','Welch''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('21000658268','Buffalo Wing BBQ Sauce','Sweet Baby Ray''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41303054116','Passion Fruit Greek Yogurt','Chobani',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('52100096364','Chips Ahoy Chunky','Nabisco',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70177031343','Lightly Salted Rounds','Tostitos',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41190400065','Heritage Flakes','Nature''s Path',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('12000508714','Frosted Flakes Chocolate','Kellogg''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41755090492','Caramel Sutra Ice Cream','Ben & Jerry''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('78742145853','Croissant Crust Chicken','DiGiorno',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('37600432252','Sipping Bone Broth Tom Basil','Swanson',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11110874054','Southwest Style Vegetables','Birds Eye',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41497605149','Strawberry Lemonade','Tropicana',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('25000042133','Spirals Mac & Cheese','Kraft',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41130589195','Peanut Butter Dark Choc Bars','Nature Valley',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41220067145','Roasted Red Pepper Sauce','Prego',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11150183065','Fruit Naturals Peaches','Del Monte',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('688267141164','Carrot Baby Food','Plum Organics',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70330606715','Apricot Preserves','Welch''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41303052082','Flip Greek Yogurt Coconut','Chobani',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('52100043672','Teddy Grahams Honey','Nabisco',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70177453909','Cantina Thin & Crispy','Tostitos',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41190400058','Optimum Power Cereal','Nature''s Path',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('12000161612','Cocoa Krispies','Kellogg''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41755090508','Everything But The Ice Cream','Ben & Jerry''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('78742041094','Personal Size Pizza Supreme','DiGiorno',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('37600226462','Crafted Bone Broth Beef','Swanson',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11110840301','Steamfresh Brussels Sprouts','Birds Eye',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41497434473','Watermelon Juice','Tropicana',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('25000155734','Bacon Mac & Cheese','Kraft',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41220632831','Homestyle Alfredo Sauce','Prego',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11150540841','Tropical Fruit Salad','Del Monte',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('688267141171','Spinach Pea Baby Food','Plum Organics',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70330606739','Peach Preserves','Welch''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('21000658282','Kickin'' Bourbon BBQ','Sweet Baby Ray''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41303054123','Mango Greek Yogurt','Chobani',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('52100096371','Chips Ahoy Reese''s','Nabisco',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70177031350','Oven Baked Scoops','Tostitos',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41190017829','Leapin'' Lemurs Cereal','Nature''s Path',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('12000508721','Froot Loops Cereal','Kellogg''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41755090515','Coconut Seven Layer Bar','Ben & Jerry''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('78742145846','Croissant Crust Pepperoni','DiGiorno',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('37600226479','Crafted Bone Broth Turkey','Swanson',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11110840295','Steamfresh Cauliflower','Birds Eye',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41497605156','Peach Mango Juice','Tropicana',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('25000155741','Jalapeno Mac & Cheese','Kraft',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41130581328','Protein Chocolate Bars','Nature Valley',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('41220632848','Italian Sausage Sauce','Prego',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('11150540858','Fruit Cocktail No Sugar','Del Monte',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('688267141188','Kale Spinach Apple Baby Food','Plum Organics',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('70330726062','Blueberry Spread','Welch''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;
INSERT INTO products (upc, product_name, brand_name, category, ingredients, image_url) VALUES ('21000658299','Maple BBQ Sauce','Sweet Baby Ray''s',NULL,NULL,NULL) ON CONFLICT (upc) DO NOTHING;

-- RECALLS (50 rows — test/demo data)
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41190468935','Organic Almond Butter','Nature''s Path','2024-01-15','Salmonella contamination','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('70038640196','Peanut Butter Cups','Reese''s','2024-01-20','Undeclared tree nuts','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('11110421234','Frozen Spinach','Green Giant','2024-02-01','Listeria monocytogenes','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41303001234','Greek Yogurt Strawberry','Chobani','2024-02-05','Mold contamination','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('52100031234','Chocolate Chip Cookies','Chips Ahoy','2024-02-10','Metal fragments','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('688267141232','Organic Baby Food Carrots','Plum Organics','2024-02-12','Lead contamination','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('12000161230','Corn Flakes Cereal','Kellogg''s','2024-02-15','Undeclared wheat','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41755001234','Vanilla Ice Cream','Ben & Jerry''s','2024-02-18','Listeria contamination','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('78742001234','Frozen Pizza Pepperoni','DiGiorno','2024-02-20','E. coli contamination','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('37600001234','Chicken Broth','Swanson','2024-02-22','Glass fragments','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('11110861234','Mixed Vegetables Frozen','Birds Eye','2024-02-25','Salmonella risk','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41497001234','Orange Juice Pulp Free','Tropicana','2024-03-01','Mold presence','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('25000001234','Macaroni & Cheese','Kraft','2024-03-05','Undeclared milk','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41130001234','Granola Bars Chocolate','Nature Valley','2024-03-08','Metal shavings','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41220001234','Tomato Sauce','Prego','2024-03-10','Glass contamination','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('11150001234','Canned Corn','Del Monte','2024-03-12','Botulism risk','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('688267001234','Fruit Pouches Mixed Berry','Plum Organics','2024-03-15','Choking hazard','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('70330001234','Grape Jelly','Welch''s','2024-03-18','Mold contamination','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('21000001234','BBQ Sauce Original','Sweet Baby Ray''s','2024-03-20','Undeclared soy','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41303091234','Greek Yogurt Vanilla','Chobani','2024-03-22','Plastic pieces','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('52100081234','Oreo Cookies','Nabisco','2024-03-25','Undeclared peanuts','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('70177001234','Salsa Medium','Tostitos','2024-03-28','Listeria risk','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41190001234','Maple Syrup','Nature''s Path','2024-04-01','Glass fragments','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('12000101234','Frosted Flakes','Kellogg''s','2024-04-03','Salmonella contamination','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41755021234','Chunky Monkey Ice Cream','Ben & Jerry''s','2024-04-05','Metal contamination','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('78742051234','Frozen Pizza Supreme','DiGiorno','2024-04-08','Foreign material','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('37600111234','Vegetable Broth','Swanson','2024-04-10','Undeclared celery','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('11110981234','Green Beans Frozen','Birds Eye','2024-04-12','Listeria presence','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41497091234','Apple Juice','Tropicana','2024-04-15','Arsenic levels','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('25000051234','Velveeta Shells & Cheese','Kraft','2024-04-18','Plastic contamination','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41130061234','Protein Bars Peanut Butter','Nature Valley','2024-04-20','Undeclared tree nuts','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41220081234','Alfredo Sauce','Prego','2024-04-22','Allergen mislabeling','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('11150081234','Canned Green Beans','Del Monte','2024-04-25','Metal fragments','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('688267121234','Organic Applesauce','Plum Organics','2024-04-28','Mold growth','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('70330081234','Strawberry Preserves','Welch''s','2024-05-01','Glass particles','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('21000081234','Honey BBQ Sauce','Sweet Baby Ray''s','2024-05-03','Undeclared mustard','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41303111234','Greek Yogurt Blueberry','Chobani','2024-05-05','E. coli risk','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('52100121234','Wheat Thins Crackers','Nabisco','2024-05-08','Salmonella contamination','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('70177081234','Queso Dip','Tostitos','2024-05-10','Listeria monocytogenes','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41190121234','Peanut Butter Crunchy','Nature''s Path','2024-05-12','Metal pieces','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('12000201234','Rice Krispies','Kellogg''s','2024-05-15','Undeclared milk','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41755101234','Half Baked Ice Cream','Ben & Jerry''s','2024-05-18','Plastic fragments','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('78742101234','Frozen Pizza Four Cheese','DiGiorno','2024-05-20','Foreign object','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('37600201234','Beef Broth','Swanson','2024-05-22','Undeclared soy','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('11111001234','Peas & Carrots Frozen','Birds Eye','2024-05-25','Listeria contamination','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41497201234','Grapefruit Juice','Tropicana','2024-05-28','Chemical contamination','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('25000101234','Easy Mac Microwave','Kraft','2024-06-01','Undeclared wheat','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41130101234','Chewy Granola Bars','Nature Valley','2024-06-03','Allergen cross-contact','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('41220101234','Marinara Sauce','Prego','2024-06-05','Glass shards','FDA',NULL) ON CONFLICT DO NOTHING;
INSERT INTO recalls (upc, product_name, brand_name, recall_date, reason, source, severity) VALUES ('11150101234','Canned Peas','Del Monte','2024-06-08','Metal contamination','FDA',NULL) ON CONFLICT DO NOTHING;
